import { createGraphQLErrorFormatter } from '@pixaeron/graphql';

const AUTH_PUBLIC_GRAPHQL_ERROR_CODES = new Set([
  'ACCOUNT_LINK_REQUIRED',
  'AUTH_ACTION_COOLDOWN',
  'CAPTCHA_INVALID',
  'CAPTCHA_REQUIRED',
  'CAPTCHA_UNAVAILABLE',
  'EMAIL_ALREADY_REGISTERED',
  'EMAIL_DELIVERY_UNAVAILABLE',
  'EMAIL_NOT_VERIFIED',
  'GOOGLE_EMAIL_NOT_VERIFIED',
  'GOOGLE_TOKEN_INVALID',
  'LEGAL_CONSENT_REQUIRED',
  'TOO_MANY_AUTH_ATTEMPTS',
  'TOO_MANY_LOGIN_ATTEMPTS',
]);

const formatAuthGraphQLError = createGraphQLErrorFormatter({
  publicCodes: AUTH_PUBLIC_GRAPHQL_ERROR_CODES,
});

export { AUTH_PUBLIC_GRAPHQL_ERROR_CODES, formatAuthGraphQLError };
